name: Deploy the React application

on:
  push:
    branches:
      - master


env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO_UI: "codeql"
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v1 # Set the Docker CLI version
        
  
      - name: Login the docker, Build and Push the Image
        run: |
          cd "$DOCKERFILEPATH"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ACCESS_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'$DOCKER_USERNAME'", "password": "'$DOCKER_PASSWORD'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
          input_string=$(curl -s -H "Authorization: Bearer $DOCKER_ACCESS_TOKEN" https://registry.hub.docker.com/v2/repositories/pushpau/$DOCKER_REPO_UI/tags | jq -r '.results | max_by(.last_updated) | .name')
          number=$(echo "$input_string" | grep -oE '[0-9]+$') && new_number=$((number + 1)) && new_string=$(echo "$input_string" | sed "s/$number$/$new_number/")
          docker build -t pushpau/$DOCKER_REPO_UI:$new_string .
          docker push pushpau/$DOCKER_REPO_UI:$new_string


